# Generated by Django 3.2 on 2021-12-23 15:59

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [

    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=512)),
                ('text', models.TextField(blank=True)),
                ('iframe', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='posts-images/')),
                ('image_alt', models.CharField(blank=True, max_length=512)),
                ('author', models.CharField(max_length=512)),
            ],
        ),
    ]
