# Generated by Django 3.2 on 2021-12-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_auto_20211218_1425'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QuoteModel',
            new_name='PostModel',
        ),
    ]
