# Generated by Django 3.2 on 2021-12-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_rename_quotemodel_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='iframe',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, upload_to='posts-images/'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='image_alt',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
