# Generated by Django 3.2 on 2021-12-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_auto_20211218_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='url',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
