# Generated by Django 3.2 on 2021-12-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_postmodel_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
